# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [1]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 1 & 2: Solutions by Mithun') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 1 & 2: Solutions by Mithun
Local Time: 2023-07-03 21:58:09
Computer ID: Mithun-Paulose

## NumPy

1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array.

In [21]:
## Your code here down
import numpy as np
import random

arr_2D = np.random.randint(1,10, (4,5))
print("Array is :")
print(arr_2D)
mean = np.mean(arr_2D)
print("Mean is :")
print(mean)
# print(mean)
#print(std) and so on
## Your code here up

Array is :
[[6 9 1 5 7]
 [4 7 3 9 5]
 [4 1 7 9 6]
 [2 2 3 2 7]]
Mean is :
4.95

2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [28]:
## Your code here down
arr_1D = np.random.rand(20)
print("Array is :")
print(arr_1D)
arr_1D = arr_1D.reshape(4,5)
print("Reshaped array is :")
print(arr_1D)
row_mean = np.mean(arr_1D, axis=1)
print("Rowwise mean is :")
print(row_mean)
## Your code here up

Array is :
[0.09409244 0.28768245 0.48456027 0.26311104 0.53043147 0.34998602
 0.41485995 0.41048639 0.74418215 0.45819221 0.30823072 0.9883267
 0.40283424 0.75342445 0.86657604 0.68684539 0.70228599 0.27707363
 0.44502333 0.46708542]
Reshaped array is :
[[0.09409244 0.28768245 0.48456027 0.26311104 0.53043147]
 [0.34998602 0.41485995 0.41048639 0.74418215 0.45819221]
 [0.30823072 0.9883267  0.40283424 0.75342445 0.86657604]
 [0.68684539 0.70228599 0.27707363 0.44502333 0.46708542]]
Rowwise mean is :
[0.33197554 0.47554134 0.66387843 0.51566275]

3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [30]:
## Your code here down
arr_2D = np.random.randint(1,100, (5,5))
print("Array is :")
print(arr_2D)
col_std = np.std(arr_2D, axis=0)
print("Standard deviations of each column are :")
print(col_std)
## Your code here up

Array is :
[[27 27 68 76 75]
 [89 44 19  7 79]
 [87 57  9 57  4]
 [ 5 25  1 71 99]
 [28 53 79 94 80]]
Standard deviations of each column are :
[34.31850813 13.12097557 31.97749208 29.48219802 32.76949801]

4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [35]:
## Your code here down
arr_1D = np.random.uniform(-10, 10, (15))
print("Array is :")
print(arr_1D)
arr_1D = [i*-1 if i<0 else i for i in arr_1D]
print("Replaced Array is :")
print(arr_1D)
## Your code here up

Array is :
[-5.8238187   0.65033149  3.52170785  1.98173318 -6.36815716 -6.44412608
  0.45104047  4.47571543  8.38543867 -2.55896655 -3.28326556  1.35865352
  4.99078747 -4.86872457 -1.85519009]
Replaced Array is :
[5.823818695071004, 0.6503314917602658, 3.521707854635011, 1.9817331814950485, 6.368157163447186, 6.444126079894456, 0.45104046914295104, 4.475715428355581, 8.385438669095958, 2.5589665530483297, 3.28326555597865, 1.3586535168368723, 4.99078747474967, 4.868724571710961, 1.855190090623024]

5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [37]:
## Your code here down
arr_2D = np.random.randint(1, 100, (3,4))
print("Array is :")
print(arr_2D)
sum = np.sum(arr_2D)
print("Sum is :")
print(sum)
## Your code here up

Array is :
[[41 15 56 31]
 [ 7 62 47 30]
 [51 92 12 46]]
Sum is :
490

7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [40]:
## Your code here down
arr_2D = np.random.rand(4,6)
print("Array is :")
print(arr_2D)

col_std = np.std(arr_2D, axis=0)
print("Standard deviations of each column are :")
print(col_std)

mean = np.mean(arr_2D, axis=0)
print("Column Mean is :")
print(mean)

arr_2D = (arr_2D - mean) / col_std
print("Normalized Array is :")
print(arr_2D)
## Your code here up

Array is :
[[0.91408416 0.18814047 0.1963674  0.54902716 0.1203924  0.09030417]
 [0.34149106 0.83731333 0.43800467 0.89855608 0.66048721 0.68250035]
 [0.44175267 0.17635285 0.99536154 0.73539039 0.77254551 0.40909738]
 [0.09868419 0.54016296 0.25208782 0.33438001 0.44801069 0.71276128]]
Standard deviations of each column are :
[0.29607226 0.27420442 0.31598582 0.21046112 0.24841573 0.25095504]
Column Mean is :
[0.44900302 0.4354924  0.47045536 0.62933841 0.50035895 0.47366579]
Normalized Array is :
[[ 1.57083658 -0.90207127 -0.8674059  -0.38159663 -1.52955914 -1.52761075]
 [-0.36312744  1.46540642 -0.10269665  1.27918007  0.6445979   0.83215922]
 [-0.02448845 -0.94505969  1.66117009  0.50390297  1.0956897  -0.25729077]
 [-1.18322069  0.38172455 -0.69106753 -1.40148641 -0.21072846  0.9527423 ]]

8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [50]:
## Your code here down
arr_2D = np.random.randint(1, 100, (10,10))
print("Array is :")
print(arr_2D)
##This line is throwing an error. could not figure it out
##arr_2D = np.asarray([1 if i > 50 else 0 for i in arr_2D])
arr_2D[arr_2D<=50] = 0
arr_2D[arr_2D>50] = 1
print("Replaced Array is :")
print(arr_2D)
## Your code here up

Array is :
[[11  2 93 68 70  8 51 54 79 47]
 [81 19 10 70 44 93 82 42 40 84]
 [52 66 71 20 27 37 86 91 72 97]
 [ 8 61 41 19 89 75 85 26  4 72]
 [65 38  7  7 12 29  5 81 13 24]
 [ 3 39 49 94 66 93 70 70 97 67]
 [73 88 89  5 61 10 26  1 11 67]
 [21 53 29 62 74 38 93 63 78 29]
 [22  9 68 62 56 43 69 85 12 19]
 [89 58 98 45 53 45  9 81 77 88]]
Replaced Array is :
[[0 0 1 1 1 0 1 1 1 0]
 [1 0 0 1 0 1 1 0 0 1]
 [1 1 1 0 0 0 1 1 1 1]
 [0 1 0 0 1 1 1 0 0 1]
 [1 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 1 1 1 1 1 1]
 [1 1 1 0 1 0 0 0 0 1]
 [0 1 0 1 1 0 1 1 1 0]
 [0 0 1 1 1 0 1 1 0 0]
 [1 1 1 0 1 0 0 1 1 1]]

9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [57]:
## Your code here down
arr_1D = np.random.rand(50)
print("Array is :")
print(arr_1D)

vals_greater = (arr_1D>0.5).sum()
print("Number of elements greater than 0.5 is :")
print(vals_greater)
## Your code here up

Array is :
[0.53308881 0.57806018 0.64808843 0.45997963 0.69206817 0.67120213
 0.73633166 0.09685857 0.6166518  0.98560462 0.74305015 0.45854446
 0.33272372 0.15854253 0.71983722 0.81714695 0.4551164  0.10289899
 0.72029599 0.20192742 0.72826357 0.85971972 0.00671674 0.43160333
 0.20470961 0.1125708  0.42927935 0.63310836 0.92240359 0.74620377
 0.29840004 0.81875881 0.09544915 0.65186997 0.08414119 0.76125658
 0.64353525 0.56321936 0.46223752 0.24215157 0.42313611 0.21871535
 0.7302715  0.74987145 0.45036762 0.46249075 0.38434362 0.59272246
 0.19815025 0.50497544]
Number of elements greater than 0.5 is :
26

10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [62]:
## Your code here down
arr_2D = np.random.uniform(-1, 1, (5,5))
print("Array is :")
print(arr_2D)

max_array = arr_2D.max(axis=1)
print("Max Array is :")
print(max_array)
min_array = arr_2D.min(axis=1)
print("Min Array is :")
print(min_array)

result = np.absolute(np.absolute(max_array ) - np.absolute(min_array))
print("Absolute difference array is :")
print(result)
## Your code here up

Array is :
[[ 0.63776358  0.62692    -0.65692015 -0.43469962 -0.93786549]
 [ 0.63636231 -0.65420408 -0.40190055  0.44367985 -0.89054297]
 [-0.15088447  0.70945285 -0.8248734   0.25008795  0.67837428]
 [ 0.96441573 -0.38162661 -0.59682259 -0.19205636 -0.9079693 ]
 [ 0.77222267 -0.6691395  -0.71676882 -0.31397072 -0.58389528]]
Max Array is :
[0.63776358 0.63636231 0.70945285 0.96441573 0.77222267]
Min Array is :
[-0.93786549 -0.89054297 -0.8248734  -0.9079693  -0.71676882]
Absolute difference array is :
[0.30010191 0.25418066 0.11542055 0.05644643 0.05545385]

## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part.

In [63]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(40):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # random lat with 2 decimal points
        'temperature': round(random.uniform(18, 25), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 50), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [108]:
df = pd.DataFrame(farms)

1. Select the rows where the temperature is above 20 degrees Celsius.

In [68]:
## Your code here down
df[df['temperature']>20]

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
2     Farm 3   -101.26     50.33         24.9           23.7  dark brown
3     Farm 4   -100.71     50.22         25.0           21.3  dark brown
5     Farm 6   -102.29     50.21         24.4           24.0        None
6     Farm 7   -101.78     50.94         24.2           29.3  dark brown
7     Farm 8   -101.87     50.53         20.5           40.0       brown
8     Farm 9   -101.93     50.68         25.0           45.8       brown
9    Farm 10   -100.02     50.28         23.9           41.7       black
10   Farm 11   -103.47     50.15         20.7           45.5        None
12   Farm 13   -104.59     50.56         23.7           42.8        None
13   Farm 14   -103.99     51.09         22.6           25.3        None
16   Farm 17   -101.52     50.94         24.8           27.0  dark brown
17   Farm 18   -103.50     50.29         22.1           21.6       brown
18   Farm 19   -102.39     51.12         23.8           24.2       black
19   Farm 20   -100.86     51.93         20.6           38.7  dark brown
20   Farm 21   -100.71     51.49         22.3           45.6       brown
21   Farm 22   -104.09     51.20         21.9           24.9       brown
24   Farm 25   -100.45     51.23         21.6           40.1        gray
25   Farm 26   -102.13     51.01         24.0           28.7       black
26   Farm 27   -101.06     50.38         22.7           36.6        gray
27   Farm 28   -100.59     51.20         24.0           37.5       brown
28   Farm 29   -102.16     50.14         23.0           28.5       black
30   Farm 31   -103.45     50.91         23.7           39.0       black
32   Farm 33   -103.17     50.41         21.4           35.1       brown
33   Farm 34   -103.66     50.36         23.3           20.8        None
35   Farm 36   -100.17     51.88         24.4           38.5        None
36   Farm 37   -103.96     50.08         23.3           45.0       black
37   Farm 38   -102.84     51.79         20.7           35.0       black
39   Farm 40   -100.90     51.65         23.2           23.3        None

2. Sort the DataFrame by precipitation in descending order.

In [71]:
## Your code here down
df.sort_values(by=['precipitation'], ascending=False)

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
8     Farm 9   -101.93     50.68         25.0           45.8       brown
20   Farm 21   -100.71     51.49         22.3           45.6       brown
10   Farm 11   -103.47     50.15         20.7           45.5        None
36   Farm 37   -103.96     50.08         23.3           45.0       black
15   Farm 16   -101.26     50.52         18.2           44.0        None
22   Farm 23   -101.88     50.87         18.5           43.5       black
12   Farm 13   -104.59     50.56         23.7           42.8        None
0     Farm 1   -103.76     50.91         19.7           42.5        None
9    Farm 10   -100.02     50.28         23.9           41.7       black
24   Farm 25   -100.45     51.23         21.6           40.1        gray
7     Farm 8   -101.87     50.53         20.5           40.0       brown
30   Farm 31   -103.45     50.91         23.7           39.0       black
19   Farm 20   -100.86     51.93         20.6           38.7  dark brown
35   Farm 36   -100.17     51.88         24.4           38.5        None
27   Farm 28   -100.59     51.20         24.0           37.5       brown
26   Farm 27   -101.06     50.38         22.7           36.6        gray
32   Farm 33   -103.17     50.41         21.4           35.1       brown
37   Farm 38   -102.84     51.79         20.7           35.0       black
4     Farm 5   -101.91     50.86         19.2           34.1        None
14   Farm 15   -101.23     51.33         19.7           33.7       black
34   Farm 35   -103.13     50.36         19.7           33.7        None
38   Farm 39   -100.37     51.87         19.9           32.0        None
31   Farm 32   -104.09     51.17         18.4           31.2       black
6     Farm 7   -101.78     50.94         24.2           29.3  dark brown
29   Farm 30   -104.50     51.60         18.6           28.7       brown
25   Farm 26   -102.13     51.01         24.0           28.7       black
28   Farm 29   -102.16     50.14         23.0           28.5       black
23   Farm 24   -104.41     51.38         19.8           27.6       brown
16   Farm 17   -101.52     50.94         24.8           27.0  dark brown
13   Farm 14   -103.99     51.09         22.6           25.3        None
21   Farm 22   -104.09     51.20         21.9           24.9       brown
18   Farm 19   -102.39     51.12         23.8           24.2       black
5     Farm 6   -102.29     50.21         24.4           24.0        None
2     Farm 3   -101.26     50.33         24.9           23.7  dark brown
39   Farm 40   -100.90     51.65         23.2           23.3        None
11   Farm 12   -103.49     50.62         19.8           22.4        None
1     Farm 2   -101.33     51.62         18.0           21.9  dark brown
17   Farm 18   -103.50     50.29         22.1           21.6       brown
3     Farm 4   -100.71     50.22         25.0           21.3  dark brown
33   Farm 34   -103.66     50.36         23.3           20.8        None

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [75]:
## Your code here down
df[(df['farm_lat'] >= 51.00) & (df['farm_lat'] <= 51.15)]

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation soil_type
13   Farm 14   -103.99     51.09         22.6           25.3      None
18   Farm 19   -102.39     51.12         23.8           24.2     black
25   Farm 26   -102.13     51.01         24.0           28.7     black

 4. Calculate the standard deviation of precipitation for each soil type.

In [112]:
## Your code here down
print("Standard Deviations: ")

print("Black: {}".format((df['soil_type'] == 'black').std()))
print("Gray: {}".format((df['soil_type'] == 'gray').std()))
print("Dark Brown: {}".format((df['soil_type'] == 'dark brown').std()))
print("Brown: {}".format((df['soil_type'] == 'brown').std()))
print("None: {}".format((df['soil_type'] == None).std()))

## Your code here up

Standard Deviations:
Black: 0.4385290096535146
Gray: 0.22072142786315221
Dark Brown: 0.36162028533978946
Brown: 0.42290206176626033
None: 0.0

5. Calculate the cumulative sum of precipitation for each soil type.

In [125]:
## Your code here down
print("Cumulative sum of precipitaions: ")

print("Black : ")
dfBlack = df.loc[(df['soil_type'] == 'black')].copy()
dfBlack['sum'] = dfBlack['precipitation'].cumsum()
print(dfBlack.iloc[-1]['sum'])

print("Gray : ")
dfGray = df.loc[(df['soil_type'] == 'gray')].copy()
dfGray['sum'] = dfGray['precipitation'].cumsum()
print(dfGray.iloc[-1]['sum'])

print("Dark Brown : ")
dfDarkBrown = df.loc[(df['soil_type'] == 'dark brown')].copy()
dfDarkBrown['sum'] = dfDarkBrown['precipitation'].cumsum()
print(dfDarkBrown.iloc[-1]['sum'])

print("Brown : ")
dfBrown = df.loc[(df['soil_type'] == 'brown')].copy()
dfBrown['sum'] = dfBrown['precipitation'].cumsum()
print(dfBrown.iloc[-1]['sum'])

print("None : ")
dfNone = df.loc[(df['soil_type'] == None)].copy()
if dfNone.size > 0:
    dfNone['sum'] = dfNone['precipitation'].cumsum()
    print(dfNone.iloc[-1]['sum'].notnull())


## Your code here up

Cumulative sum of precipitaions:
Black :
350.5
Gray :
76.7
Dark Brown :
161.89999999999998
Brown :
306.8
None :

6. Determine the top 3 farms with the highest average temperature.

In [129]:
## Your code here down

df1 = df.sort_values('temperature',ascending = False).head(3)
print (df1)
## Your code here up

  farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
3    Farm 4   -100.71     50.22         25.0           21.3  dark brown
8    Farm 9   -101.93     50.68         25.0           45.8       brown
2    Farm 3   -101.26     50.33         24.9           23.7  dark brown

7. Find farms in each soil type that have the highest temperature.

In [130]:
## Your code here down
print(dfBlack.sort_values('temperature',ascending = False).head(1))
print(dfGray.sort_values('temperature',ascending = False).head(1))
print(dfDarkBrown.sort_values('temperature',ascending = False).head(1))
print(dfBrown.sort_values('temperature',ascending = False).head(1))
print(dfNone.sort_values('temperature',ascending = False).head(1))

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation soil_type    sum
25   Farm 26   -102.13     51.01         24.0           28.7     black  171.8
   farm_name  farm_lon  farm_lat  temperature  precipitation soil_type   sum
26   Farm 27   -101.06     50.38         22.7           36.6      gray  76.7
  farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type   sum
3    Farm 4   -100.71     50.22         25.0           21.3  dark brown  66.9
  farm_name  farm_lon  farm_lat  temperature  precipitation soil_type   sum
8    Farm 9   -101.93     50.68         25.0           45.8     brown  85.8
Empty DataFrame
Columns: [farm_name, farm_lon, farm_lat, temperature, precipitation, soil_type]
Index: []

8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [138]:
## Your code here down
tot_prec = df['precipitation'].sum()
df_tot_prec = df.copy()
df_tot_prec['percentage_tot_prec'] = (df['precipitation'] / tot_prec) * 100
print(df_tot_prec)
## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
0     Farm 1   -103.76     50.91         19.7           42.5        None
1     Farm 2   -101.33     51.62         18.0           21.9  dark brown
2     Farm 3   -101.26     50.33         24.9           23.7  dark brown
3     Farm 4   -100.71     50.22         25.0           21.3  dark brown
4     Farm 5   -101.91     50.86         19.2           34.1        None
5     Farm 6   -102.29     50.21         24.4           24.0        None
6     Farm 7   -101.78     50.94         24.2           29.3  dark brown
7     Farm 8   -101.87     50.53         20.5           40.0       brown
8     Farm 9   -101.93     50.68         25.0           45.8       brown
9    Farm 10   -100.02     50.28         23.9           41.7       black
10   Farm 11   -103.47     50.15         20.7           45.5        None
11   Farm 12   -103.49     50.62         19.8           22.4        None
12   Farm 13   -104.59     50.56         23.7           42.8        None
13   Farm 14   -103.99     51.09         22.6           25.3        None
14   Farm 15   -101.23     51.33         19.7           33.7       black
15   Farm 16   -101.26     50.52         18.2           44.0        None
16   Farm 17   -101.52     50.94         24.8           27.0  dark brown
17   Farm 18   -103.50     50.29         22.1           21.6       brown
18   Farm 19   -102.39     51.12         23.8           24.2       black
19   Farm 20   -100.86     51.93         20.6           38.7  dark brown
20   Farm 21   -100.71     51.49         22.3           45.6       brown
21   Farm 22   -104.09     51.20         21.9           24.9       brown
22   Farm 23   -101.88     50.87         18.5           43.5       black
23   Farm 24   -104.41     51.38         19.8           27.6       brown
24   Farm 25   -100.45     51.23         21.6           40.1        gray
25   Farm 26   -102.13     51.01         24.0           28.7       black
26   Farm 27   -101.06     50.38         22.7           36.6        gray
27   Farm 28   -100.59     51.20         24.0           37.5       brown
28   Farm 29   -102.16     50.14         23.0           28.5       black
29   Farm 30   -104.50     51.60         18.6           28.7       brown
30   Farm 31   -103.45     50.91         23.7           39.0       black
31   Farm 32   -104.09     51.17         18.4           31.2       black
32   Farm 33   -103.17     50.41         21.4           35.1       brown
33   Farm 34   -103.66     50.36         23.3           20.8        None
34   Farm 35   -103.13     50.36         19.7           33.7        None
35   Farm 36   -100.17     51.88         24.4           38.5        None
36   Farm 37   -103.96     50.08         23.3           45.0       black
37   Farm 38   -102.84     51.79         20.7           35.0       black
38   Farm 39   -100.37     51.87         19.9           32.0        None
39   Farm 40   -100.90     51.65         23.2           23.3        None

    percentage_tot_prec
0              3.208031
1              1.653080
2              1.788949
3              1.607790
4              2.573973
5              1.811594
6              2.211655
7              3.019324
8              3.457126
9              3.147645
10             3.434481
11             1.690821
12             3.230676
13             1.909722
14             2.543780
15             3.321256
16             2.038043
17             1.630435
18             1.826691
19             2.921196
20             3.442029
21             1.879529
22             3.283514
23             2.083333
24             3.026872
25             2.166365
26             2.762681
27             2.830616
28             2.151268
29             2.166365
30             2.943841
31             2.355072
32             2.649457
33             1.570048
34             2.543780
35             2.906099
36             3.396739
37             2.641908
38             2.415459
39             1.758756

9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [143]:
## Your code here down

df_prec_rank = df.copy()
df_prec_rank['Precipitation_Rank'] = df_prec_rank['precipitation'].rank(ascending=True).astype(int)
print(df_prec_rank.sort_values(by=['Precipitation_Rank'], ascending=True))

## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type  \
33   Farm 34   -103.66     50.36         23.3           20.8        None
3     Farm 4   -100.71     50.22         25.0           21.3  dark brown
17   Farm 18   -103.50     50.29         22.1           21.6       brown
1     Farm 2   -101.33     51.62         18.0           21.9  dark brown
11   Farm 12   -103.49     50.62         19.8           22.4        None
39   Farm 40   -100.90     51.65         23.2           23.3        None
2     Farm 3   -101.26     50.33         24.9           23.7  dark brown
5     Farm 6   -102.29     50.21         24.4           24.0        None
18   Farm 19   -102.39     51.12         23.8           24.2       black
21   Farm 22   -104.09     51.20         21.9           24.9       brown
13   Farm 14   -103.99     51.09         22.6           25.3        None
16   Farm 17   -101.52     50.94         24.8           27.0  dark brown
23   Farm 24   -104.41     51.38         19.8           27.6       brown
28   Farm 29   -102.16     50.14         23.0           28.5       black
25   Farm 26   -102.13     51.01         24.0           28.7       black
29   Farm 30   -104.50     51.60         18.6           28.7       brown
6     Farm 7   -101.78     50.94         24.2           29.3  dark brown
31   Farm 32   -104.09     51.17         18.4           31.2       black
38   Farm 39   -100.37     51.87         19.9           32.0        None
14   Farm 15   -101.23     51.33         19.7           33.7       black
34   Farm 35   -103.13     50.36         19.7           33.7        None
4     Farm 5   -101.91     50.86         19.2           34.1        None
37   Farm 38   -102.84     51.79         20.7           35.0       black
32   Farm 33   -103.17     50.41         21.4           35.1       brown
26   Farm 27   -101.06     50.38         22.7           36.6        gray
27   Farm 28   -100.59     51.20         24.0           37.5       brown
35   Farm 36   -100.17     51.88         24.4           38.5        None
19   Farm 20   -100.86     51.93         20.6           38.7  dark brown
30   Farm 31   -103.45     50.91         23.7           39.0       black
7     Farm 8   -101.87     50.53         20.5           40.0       brown
24   Farm 25   -100.45     51.23         21.6           40.1        gray
9    Farm 10   -100.02     50.28         23.9           41.7       black
0     Farm 1   -103.76     50.91         19.7           42.5        None
12   Farm 13   -104.59     50.56         23.7           42.8        None
22   Farm 23   -101.88     50.87         18.5           43.5       black
15   Farm 16   -101.26     50.52         18.2           44.0        None
36   Farm 37   -103.96     50.08         23.3           45.0       black
10   Farm 11   -103.47     50.15         20.7           45.5        None
20   Farm 21   -100.71     51.49         22.3           45.6       brown
8     Farm 9   -101.93     50.68         25.0           45.8       brown

    Precipitation_Rank
33                   1
3                    2
17                   3
1                    4
11                   5
39                   6
2                    7
5                    8
18                   9
21                  10
13                  11
16                  12
23                  13
28                  14
25                  15
29                  15
6                   17
31                  18
38                  19
14                  20
34                  20
4                   22
37                  23
32                  24
26                  25
27                  26
35                  27
19                  28
30                  29
7                   30
24                  31
9                   32
0                   33
12                  34
22                  35
15                  36
36                  37
10                  38
20                  39
8                   40

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [145]:
## Your code here down
df_norm = df.copy()
## min max method
df_norm['temperature'] = (df_norm['temperature'] - df_norm['temperature'].min()) / (df_norm['temperature'].max() - df_norm['temperature'].min())
df_norm
## Your code here up

   farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.76     50.91     0.242857           42.5        None
1     Farm 2   -101.33     51.62     0.000000           21.9  dark brown
2     Farm 3   -101.26     50.33     0.985714           23.7  dark brown
3     Farm 4   -100.71     50.22     1.000000           21.3  dark brown
4     Farm 5   -101.91     50.86     0.171429           34.1        None
5     Farm 6   -102.29     50.21     0.914286           24.0        None
6     Farm 7   -101.78     50.94     0.885714           29.3  dark brown
7     Farm 8   -101.87     50.53     0.357143           40.0       brown
8     Farm 9   -101.93     50.68     1.000000           45.8       brown
9    Farm 10   -100.02     50.28     0.842857           41.7       black
10   Farm 11   -103.47     50.15     0.385714           45.5        None
11   Farm 12   -103.49     50.62     0.257143           22.4        None
12   Farm 13   -104.59     50.56     0.814286           42.8        None
13   Farm 14   -103.99     51.09     0.657143           25.3        None
14   Farm 15   -101.23     51.33     0.242857           33.7       black
15   Farm 16   -101.26     50.52     0.028571           44.0        None
16   Farm 17   -101.52     50.94     0.971429           27.0  dark brown
17   Farm 18   -103.50     50.29     0.585714           21.6       brown
18   Farm 19   -102.39     51.12     0.828571           24.2       black
19   Farm 20   -100.86     51.93     0.371429           38.7  dark brown
20   Farm 21   -100.71     51.49     0.614286           45.6       brown
21   Farm 22   -104.09     51.20     0.557143           24.9       brown
22   Farm 23   -101.88     50.87     0.071429           43.5       black
23   Farm 24   -104.41     51.38     0.257143           27.6       brown
24   Farm 25   -100.45     51.23     0.514286           40.1        gray
25   Farm 26   -102.13     51.01     0.857143           28.7       black
26   Farm 27   -101.06     50.38     0.671429           36.6        gray
27   Farm 28   -100.59     51.20     0.857143           37.5       brown
28   Farm 29   -102.16     50.14     0.714286           28.5       black
29   Farm 30   -104.50     51.60     0.085714           28.7       brown
30   Farm 31   -103.45     50.91     0.814286           39.0       black
31   Farm 32   -104.09     51.17     0.057143           31.2       black
32   Farm 33   -103.17     50.41     0.485714           35.1       brown
33   Farm 34   -103.66     50.36     0.757143           20.8        None
34   Farm 35   -103.13     50.36     0.242857           33.7        None
35   Farm 36   -100.17     51.88     0.914286           38.5        None
36   Farm 37   -103.96     50.08     0.757143           45.0       black
37   Farm 38   -102.84     51.79     0.385714           35.0       black
38   Farm 39   -100.37     51.87     0.271429           32.0        None
39   Farm 40   -100.90     51.65     0.742857           23.3        None